setting:
    menu:
        general:
            label: General
            sort_order: 1000
        general.setting:
            label: Setting
            parent: general
            form_class: EveryWorkflow\SettingBundle\Form\General\SettingForm
        general.web:
            label: Web
            parent: general
            form_class: EveryWorkflow\SettingBundle\Form\General\WebSettingForm
        security:
            label: Security
            sort_order: 15000
        service:
            label: Service
            sort_order: 18000
        # everyworkflow.connector:
        #     label: EveryWorkflow Connector
        #     parent: service
        #     form_class: EveryWorkflow\SettingBundle\Form\General\WebSettingForm
        advance:
            label: Advance
            sort_order: 20000
        advance.system:
            label: System
            parent: advance
            form_class: EveryWorkflow\SettingBundle\Form\Advance\SystemSettingForm
